"""empty message

Revision ID: d628ad627498
Revises: 
Create Date: 2023-10-26 09:06:31.620378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd628ad627498'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Food', sa.String(length=100), nullable=True),
    sa.Column('Water', sa.Float(), nullable=True),
    sa.Column('Protein', sa.Float(), nullable=True),
    sa.Column('Fat', sa.Float(), nullable=True),
    sa.Column('Carbohydrate', sa.Float(), nullable=True),
    sa.Column('Result', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
